### ISSUE TITLE
Enable MiMa

### ISSUE THREAD

**Issue by jatcwang** [typelevel/doobie#1975]
https://github.com/lightbend/mima

The typelevel sbt plugin should already support enabling MiMa quite easily

**Comment by armanbilge** [comment]
MiMa is enabled by default. No action is necessary.

**Comment by jatcwang** [comment]
I believe MiMa is currently disabled in doobie's build so will need to enable it once we ready to stop breaking binary compatibility between RCs

**Comment by armanbilge** [comment]
No, MiMa is enabled by default, but doesn't check compatibility for pre-releases. If you want to check binary-compatibility between RCs that requires additional configuration.

**Comment by jatcwang** [comment]
Ah cool thanks for the info. I'll close this then!
