### ISSUE TITLE
Doc: buildSite/publishSite currently broken

### ISSUE THREAD

**Issue by jatcwang** [typelevel/doobie#2133]
We need to fix current errors preventing us from building the site, or perhaps convert to using docsurus.

**Comment by matsluni** [comment]
Hi @jatcwang, I tried working on this. 

I made some fixes [here](https://github.com/matsluni/doobie/tree/fix-mdoc-2133). This fixed the errors in `15-Extensions-PostgreSQL.md` I had locally and I could succesfully create the site with `sbt makeSite`. Did you have the same errors or any others?

I am no expert in `mdoc`, so please use with caution.

**Comment by jatcwang** [comment]
Hey @matsluni thanks for your help on this! Sorry I didn't put any specific errors in the issue description as I haven't tried to reproduce the error since I last ran it. but I'm a bit surprised that `mdoc:silent` would be causing errors as it's just silencing the output.
I will try to run `publishMicrosite` (since I have push privileges), make note of the errors and post it here 🙏

**Comment by jatcwang** [comment]
I gave this a go and for me I'm getting this error when I run `docs/mdoc`

```
error: 12-Custom-Mappings.md:37:1: Expected compile errors but program compiled successfully without errors
sql"SELECT message, detail FROM log".query[LogEntry]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This block of code isn't meant to compile (which is why it's using mdoc:fail) but this seems to be an issue where it doesn't recover from the compilation failure and gives a misleading error. Perhaps it has some weird interactions with one of the compiler failures..?

To get around this I think we can remove `mdoc:fail` and adjust the content to fit.

After removing that I'm getting the errors I think you're fixing in 15-Extensions-PostgreSQL.md..need more investigation on why those are failing..

**Comment by matsluni** [comment]
Thanks for sharing.

Interesting, I checked again and locally I don't get an error in `12-Custom-Mappings.md:37` when I am trying to build the site with `sbt makeSite` (it only fails if I am removing the `fail` from `mdoc`) 🤔

**Comment by jatcwang** [comment]
I had time to take another look. It's really odd indeed why only I'm getting `12-Custom-Mappings.md`. I've switched the JVM version too but the error remains.

I had a closer look at your changes and it looks good to me. 
I have fixed actually running makeSite in CI in https://github.com/typelevel/doobie/commits/fix_makeSite_skipped/, would you be able to incorporate that into your branch and raise a PR? Thank you! 😄
