### ISSUE TITLE
Docker command in CONTRIBUTING.md has several problems (including Apple Silicon)

### ISSUE THREAD

**Issue by dmamonov** [typelevel/doobie#2149]
See:
https://github.com/typelevel/doobie/blob/main/CONTRIBUTING.md

**part 1**

At the first place the documentation suggest to run:
```sh
$ docker-compose up -d --force-update 
```

But (seems) there is no such parameter.
```
unknown flag: --force-update
```

Maybe `--force-recreate` was implied?

**part 2**
Running just ` docker-compose up` on MacBook Air M1 output:

```sh
$ docker-compose up                   
[+] Running 1/2
 ✘ postgres Error                                                                                                                 1.7s 
 ⠧ mysql Pulling                                                                                                                  1.7s 
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Maybe some other image with Apple Silicon support should be used.

**part 3**
After updating Docker to the most recent (27-Nov-2024), there is no `docker-compose` command any more.

Seems `docker compose` should be used instead.

**Comment by dmamonov** [comment]
Suggestion for fix

Use command:
```
docker compose up -d --force-recreate
```

Use docker image:
```
mysql:8.0
```
instead of `mysql:8.0-debian`.

**Comment by jatcwang** [comment]
Updated M1 instructions in #2155 . Thanks!
