### ISSUE TITLE
Composite derivation from nested single-element case classes

### ISSUE THREAD

**Issue by brinklec** [typelevel/doobie#662]
In certain cases, composite seems not to be found for a multi-element case class whose elements are single-element case classes.  

Some of these can be resolved by ensuring that the single-element case classes are in-line rather than imported.  Those we think may be scalac-related.

There can also be an issue with automated composite derivation of products for nested case classes, even when the single-element case classes are in-line. This is even harder to reproduce, but I'm seeing it right now in my project.  

This file [compositeIssueUpdate3.txt](https://github.com/tpolecat/doobie/files/1887948/compositeIssueUpdate3.txt) is lifted directly from my project. This time I have only commented out dependencies on my other files (imports, typeclass instances at bottom of file, "extends" annotation on join fields case class).  As-is, it will compile, but in my project with the commented material uncommented, .deriveComposite was failing for both table and the user view with join fields added.  The file illustrates how I am working around these failures with Composite.zip and .imap.

****

The workaround below may not work if additional single-element case classes (e.g., for join columns for user view) are defined after the nested one for the table, and then a second nested one is defined that includes the table columns followed by the join columns.  At least at this iteration, the issue seems to be independent of any typeclasses for tables or user views or their composites.  Also, .deriveComposite is successfully called on all the single-element case classes.  This should not be necessary, but provides a sanity check.  The composite it is failing to derive is just an HList of the single-element types it has no trouble with.

For some reason I do not understand,
[compositeIssueUpdate2a.txt](https://github.com/tpolecat/doobie/files/1886079/compositeIssueUpdate2a.txt) compiles last time I tried, but
[compositeIssueUpdate2b.txt](https://github.com/tpolecat/doobie/files/1886080/compositeIssueUpdate2b.txt), which is the same file with only comments added, gets the same error I see in my real project.

Another example using the new .deriveComposite in doobie 0.5.2, Typelevel Scala 2.12.4, sbt 1.1.0 is in [compositeIssueUpdate.txt](https://github.com/tpolecat/doobie/files/1874409/compositeIssueUpdate.txt).  This one we determined could be worked around by in-lining the nested case classes (or including them with the main case class and its companion when pasting in paste mode).

If you paste in to repl up through the single-element case classes, then separately paste in the main case class and companion object in paste mode, you should see the same error I get in my real project.

As discussed in further comments below, this minimal example reproduces the same error in repl that I get in my real project with many files, but if you take the script as-is and wrap it in an object, it will compile.  (In my real project, an object containing the typeclass and an object containing the single-element case classes are imported in a file containing the concrete type and corresponding typeclass instances.) Also, if you paste in the single-element case classes at the same time as the main case class and companion object in paste mode, it gets no error.

Issue originally reported for doobie 0.5.0-M13, Typelevel Scala 2.12.4, sbt 1.1.0.  Old example with less clean source : [compositeIssue.txt](https://github.com/tpolecat/doobie/files/1625182/compositeIssue.txt)

**Comment by brinklec** [comment]
FYI, issue was eliminated by a major refactoring that included elimination of type constraints in typeclass and extension methods; eliminating `Rec` class hierarchy; splitting up very large typeclass; indexing typeclasses directly with case classes representing record types and extending nothing, instead of with abstract types that old case classes extended; and locating implicits for Composites in companion objects for the respective case classes.

**Comment by brinklec** [comment]
Upgraded to 0.5.2, and converted 54 typeclass instances to use the new .deriveComposite.  Now, 16 of them that were compiling fine again get Composite Not Found error.  Code base has changed somewhat, but the case class pattern is the same as before (each element of a multi-element case class is a single-element case class with a String, Int, or Option thereof).

**Comment by tpolecat** [comment]
Can you provide a minimal example?

**Comment by brinklec** [comment]
Will do later today.

**Comment by brinklec** [comment]
[compositeIssueUpdate.txt](https://github.com/tpolecat/doobie/files/1874409/compositeIssueUpdate.txt)

**Comment by brinklec** [comment]
Uploaded minimal updated example just now…

**Comment by srp** [comment]
I just compiled compositeIssueUpdate.txt fine with lightbend scala-2.12.4, doobie-0.5.2, sbt-1.1.0. Is this a problem with the typelevel compiler?

**Comment by srp** [comment]
Nevermind, I was able to finally figure out how to use the typelevel compiler (their "Optional" step isn't really optional), and I was able to compile compositeIssueUpdate.txt with it as well.

**Comment by brinklec** [comment]
compositeIssueUpdate.txt was intended as a repl example.  As noted in comment in the file, it gets the same error in repl at the same point that I get it in my real project.  I agree, if you wrap this script as-is in an object and compile, it compiles.  I'm concerned about the issue in my real project, which the repl example reproduces.

**Comment by srp** [comment]
I'm still not reproducing:

```
Welcome to Typelevel Scala 2.12.4-bin-typelevel-4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import doobie._, doobie.implicits._

// GIVEN:

  // TYPECLASS FOR TABLE COMPOSITES

  trait TblComp[B] {
    def comp: Composite[B]
  }

  object TblComp {
    def apply[B](implicit comp: TblComp[B]): TblComp[B] = comp
  }

  implicit class TblCompOps[B](b: B) {
    def comp(implicit tblComp: TblComp[B]): Composite[B] = tblComp.comp
  }

  case class TlmFuncId(value: Int)
  case class FmId(value: Int)
  case class Ss(value: String)
  case class FuncNo(value: Int)
  case class Name(value: String)
  case class Descr(value: Option[String])
  case class Src(value: String)
  case class TlmSubtype(value: String) 
  case class NrmInd(value: Option[String])
  case class MemBlkNo(value: Option[String])
  case class MemBlkOffs(value: Option[String])
  case class TlmCat(value: Option[String])
  case class Prom(value: Option[String])
  case class ShowHide(value: Option[String])
  case class FmtGrpIdOpt(value: Option[Int])
  case class CurveIdOpt(value: Option[Int])

// Exiting paste mode, now interpreting.

import doobie._
import doobie.implicits._
defined trait TblComp
defined object TblComp
defined class TblCompOps
defined class TlmFuncId
defined class FmId
defined class Ss
defined class FuncNo
defined class Name
defined class Descr
defined class Src
defined class TlmSubtype
defined class NrmInd
defined class MemBlkNo
defined class MemBlkOffs
defined class TlmCat
defined class Prom
defined class ShowHide
defined class FmtGrpIdOpt
defined class CurveIdOpt

scala> :paste
// Entering paste mode (ctrl-D to finish)

 case class TlmFuncTblRec(id: TlmFuncId, fmId: FmId, ss: Ss,
                        funcNo: FuncNo, name: Name,
                        descr: Descr, src: Src, subtype: TlmSubtype,                         
                        nrmInd: NrmInd, trgBlkNo: MemBlkNo, 
                        trgBlkOffs: MemBlkOffs, category: TlmCat, 
                        prom: Prom, showHide: ShowHide, 
                        fmtGrpId: FmtGrpIdOpt, curveId: CurveIdOpt)

  object TlmFuncTblRec {

    implicit val comp: Composite[TlmFuncTblRec] = Composite.deriveComposite[TlmFuncTblRec]()
  }

// Exiting paste mode, now interpreting.

defined class TlmFuncTblRec
defined object TlmFuncTblRec
```

**Comment by brinklec** [comment]
In any case, I think these observations should probably help clarify the nature of the issue.  

It seems to occur (at least in this and some other instances) when the dependencies are imported in compiled code, or sequentially pasted in repl, but not when they are in-lined, or when they are pasted together with the main code in paste mode.

**Comment by brinklec** [comment]
Tested another variant, a compromise with typeclass definition in an import, but single-element case classes in-lined.  This compiles.  

I don't understand why it should compile with them in-line, but not when they are imported.  Had hoped for one central list of column types so they could be reused, and the application would know when two columns in different tables have the same strong type.  But there is a plus to having the definitions locally visible, and it should not be too bad to have to call .value a few more times when populating one record type with data from another record type, so this could be a viable workaround.

**Comment by brinklec** [comment]
[compositeIssueUpdate2a.txt](https://github.com/tpolecat/doobie/files/1886079/compositeIssueUpdate2a.txt)
[compositeIssueUpdate2b.txt](https://github.com/tpolecat/doobie/files/1886080/compositeIssueUpdate2b.txt)

**Comment by jatcwang** [comment]
Closing old tickets that are seems no longer relevant (Probably already addressed at some point in the past releases)
