### ISSUE TITLE
Composite not found for large case class in presence of other structure

### ISSUE THREAD

**Issue by brinklec** [typelevel/doobie#671]
[compositeIssue2.txt](https://github.com/tpolecat/doobie/files/1658373/compositeIssue2.txt)
When attached file is saved as .scala and compiled with doobie 0.5.0-M13, Typelevel Scala 2.12.4, sbt 1.1.0, composites are not found for TlmFuncRs.rsComp or TlmFuncRs.tblComp in instance of large Recset typeclass with dependencies (excerpted here).  

Elements of the two affected case classes are all Int, String, or Option thereof.  

Commented text at end of file shows composite found for one of them in repl without all the additional structure.  Additional structure should not prevent composite resolution.

As noted in comment in the file, removing unused parameters to the two functions in the typeclass and instances allows both composites to be found in this version with no other change, but only allows one of them to be found in the full project, which has yet more typeclass instances and their dependencies in the corresponding file.  Presence or absence of an unused value parameter to an enclosing function should not affect composite resolution either.

**Comment by brinklec** [comment]
FYI, issue was eliminated by a major refactoring that included elimination of type constraints in typeclass and extension methods; eliminating `Rec` class hierarchy; splitting up very large typeclass; indexing typeclasses directly with case classes representing record types and extending nothing, instead of with abstract types that old case classes extended; and locating implicits for Composites in companion objects for the respective case classes.

**Comment by jatcwang** [comment]
Issue is most likely fixed & no longer relevant
