### ISSUE TITLE
Param not found for simple type in nested case class

### ISSUE THREAD

**Issue by brinklec** [typelevel/doobie#683]
[ParamNotFoundIssue.txt](https://github.com/tpolecat/doobie/files/1742991/ParamNotFoundIssue.txt)
(See code in above file.)
Hit a Param Not Found error in a simple parameterized query with a single Int parameter returning an Option[Int], in body of a function that takes a large nested case class as input, where all component case classes are single-element Int or String or Option thereof, and there is no issue finding the Composite for the large nested case class.

**Comment by brinklec** [comment]
Ironically but happily, my typeclass-based generics are working well enough now that I can work around this issue by substituting the appropriate generic query.  The generic query does a good deal more work than the problematic simple one here, which is why I initially tried the above, but it works.

**Comment by jatcwang** [comment]
This is most likely fixed at some point
